name: Code Review with Anthropic and Pylint
on:
  pull_request:
    types:
      - opened
      - synchronize
    
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pylint
        run: pip install pylint

      - name: Code Review
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          CLAUDE_MODEL: "claude-3-5-sonnet-20240620"
          exclude: "yarn.lock,dist/**"
